version: '3'

services:
  laravel:
    build: ./docker/php
    volumes:
    - ./server:/var/www

  nginx:
    image: nginx
    ports:
    - 8080:80
    volumes:
    - ./server:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - laravel

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  php-my-admin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8088:80"
    environment:
      MYSQL_USERNAME: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
